// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAidb498DjFnf79cc9V0n_sl-AP6mWJgNc',
    appId: '1:306999069151:web:fafb62550d46896f1edc6a',
    messagingSenderId: '306999069151',
    projectId: 'motivationalapp-5d0ed',
    authDomain: 'motivationalapp-5d0ed.firebaseapp.com',
    storageBucket: 'motivationalapp-5d0ed.appspot.com',
    measurementId: 'G-JYG00PQF4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHR51MWloZDwTW6ta-IGExSp9mZ-uwvSc',
    appId: '1:306999069151:android:af713669d18760b71edc6a',
    messagingSenderId: '306999069151',
    projectId: 'motivationalapp-5d0ed',
    storageBucket: 'motivationalapp-5d0ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnlrPLO828Li4LJgVuDd8IhNVEykOFUcI',
    appId: '1:306999069151:ios:8e2e1d48d9dd28d31edc6a',
    messagingSenderId: '306999069151',
    projectId: 'motivationalapp-5d0ed',
    storageBucket: 'motivationalapp-5d0ed.appspot.com',
    iosClientId: '306999069151-n4lo1geboliq6bqlq2ahovhu9l39c260.apps.googleusercontent.com',
    iosBundleId: 'com.example.appwrite',
  );
}
